name: Upload Python Package

on:
  release:
    types: [created]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.6.x'

    - name: Install dependencies
      run: |
        cd demo
        python -m pip install --upgrade pip
        pip install setuptools wheel
        pip install -r requirements.txt
        pip install twine
    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        cd demo
        python setup.py sdist bdist_wheel
        twine upload dist/*