name: build

on:
  push:
    branches:
      - main
    paths:
      - 'demo/**'
      - '.github/workflows/ci-in-demo-folder.yml'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.7.x'

    - name: Install dependencies
      run: |
        cd demo
        python -m pip install --upgrade pip
        pip install setuptools wheel
        pip install -r requirements.txt

    - name: Build
      run: |
        cd demo
        python setup.py sdist bdist_wheel

    - name: Test
      env:
        TEST_ENV: ${{secrets.TEST_ENV}}
      run: |
        cd demo
        pip install pytest
        pytest